travis:
  secure:
    BINSTAR_TOKEN: 4YW0CM4tmor/1cKlqSJNHdCXjNjvEFFj1x7hZPZnOFkKAL60lSHO+S1VpytFGop6ISyr423jYcdtiZJgRJAN9lrOdXQ4/bjYlhc8LCa2pRsSXa1D5Ci/9Xf9J7a7uCe0vqfdJQNc3ZNJuuiJ8qgpcOirCl/cblfZy/nVeEnYUvaFm098rGIW0x+dUDc9bljk0gkVgJpxjmtKrxNGPwXae8gZ5n54EuSZKOWCpMk7e/uwUrh5/v/EfI3p0xbxofDWuY6WyZ7FipRt+U4qoG9WKYvtPQOa9D87ytU9YofdEcUlLX7YQVE3barxgK5M/Kma7T22Pn4zr5Uow0hUoVywel/Pmpfbh0L3I6t7e7F7+nkgTMnxfizdIq2jV6mUi8EMDv05Na373tvqZ9OKhFUtaN0CptoLhX5C4sScrjIa+OjV6UzwpElTBN8HLPQ0UQfrsqNuutQ532URLpPBsRwM9JUZ4rpqcz6zhZts8a3SwtlX/PAC2ssUqdnz1gMIr3DzLY8OetwEMGih6EzPqeHQwEA5hu45m+U3DSuBxU8cxkVjHwAW6lxelrbIKcXw2E2AyFoReJvx7zao71FsTgblDs7OG08txf9dq/kykrvXGgLat4zsuuhrTdOFNK3FAuvZBI+CW6a5eoYBjhPhMVw1XWd0LqakTRsFKG+gktFKuGE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
